version: '3.7'

services:
  web:
    build: .
    volumes:
      - ./application:/app
    ports:
      - 8000:8000
    env_file:
      - application/.env
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:12.1-alpine
    env_file:
      - application/.env
    volumes:
      - "./local/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
